export const GET_PROFILE="GET_PROFILE";
export const PROFILE_ERR="PROFILE_ERR";
export const CLEAR_PROFILE="CLEAR_PROFILE";
export const CREATE_PROFILE="CREATE_PROFILE";
export const UPDATE_PROFILE="UPDATE_PROFILE";
export const UPDATE_EDUCATION="UPDATE_EDUCATION";
export const DELETE_ACCOUNT="DELETE_ACCOUNT";