export const GET_PROFILE="GET_PROFILE";
export const PROFILE_ERR="PROFILE_ERR";
export const CLEAR_PROFILE="CLEAR_PROFILE";
export const CREATE_PROFILE="CREATE_PROFILE";
export const UPDATE_PROFILE="UPDATE_PROFILE";
export const UPDATE_EDUCATION="UPDATE_EDUCATION";
export const DELETE_ACCOUNT="DELETE_ACCOUNT";

export const GET_PROFILES="GET_PROFILES";

export const GET_VISITING_PROFILE="GET_VISITING_PROFILE";

export const GET_VISITING_USER="GET_VISITING_USER";
export const CLEAR_VISITING_USER="GET_VISITING_USER";
export const CLEAR_VISITING_PROFILE="CLEAR_VISITING_PROFILE"